<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-QS76CGE" failures="1" tests="2" name="RegisterTest" time="127.43" errors="0" timestamp="2023-09-23T10:40:32 GMT">
  <testcase classname="tests.RegisterTest" name="RegisterAccount" time="26.69">
    <failure type="java.lang.AssertionError" message="expected [Successful] but found [Failure]">
      <![CDATA[java.lang.AssertionError: expected [Successful] but found [Failure]
at tests.RegisterTest.RegisterAccount(RegisterTest.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- RegisterAccount -->
  <testcase classname="tests.RegisterTest" name="RegisterAccount" time="25.674"/>
</testsuite> <!-- RegisterTest -->
